server:
    port: 80
    
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html
#spring.thymeleaf.check-template-location=true
#spring.thymeleaf.mode=LEGACYHTML5
spring:
    http:
        encoding:
            force: true
        multipart:
            # 上传文件总的最大值
            max-request-size: 10MB
            # 单个文件的最大值
            max-file-size: 10MB
    thymeleaf:
        # 关闭页面缓存
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: utf-8
        content-type: text/html
        check-template-location: true
        mode: LEGACYHTML5
    datasource:
        url: jdbc:mysql://172.17.77.24/chat_room?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.gu.chatroom.config
    
#management:
#    add-application-context-header: false